import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/ThemeProvider';
// import { Toaster } from '@/components/ui/toaster'; // Placeholder for Sonner or similar

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Production App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Placeholder for AuthProvider */}
          {/* Placeholder for StoreProvider (Zustand) */}
          {children}
          {/* <Toaster /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
